name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Build and push image
        run: |
          IMAGE=us-central1-docker.pkg.dev/sanctra-prod/sanctra-docker/sanctra-asr-gpu:${{ github.sha }}
          docker build -f Dockerfile.gpu -t $IMAGE .
          docker push $IMAGE
